spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jathu1994/project-manager-config-store
          search-paths:
          - 'service-config/*service'
#          username: jathu10061994@gmail.com
#          password: ja4044868
          

debug: true